### ISSUE TITLE
Codelens not resolving references, always reports zero. 

### ISSUE THREAD

**Issue by WillEhrendreich** [ionide/Ionide-vim#59] opened 2022-07-14 20:29 UTC
Zero references reported, when there are references. 
![image](https://user-images.githubusercontent.com/55286472/179077378-277d57cb-7d86-41da-9ce6-66fdf20ac556.png)
**To Reproduce**
have.. a file.. open? sorry, I know that's no help. 

**Expected behaviour**
That it would find references, not only within the same file, but from other projects within the solution.

**Environment (please complete the following information):**
 - OS: Windows 
 - Vim / Neovim version: 0.7.2
 - dotnet SDK version: 6
 - mono / .Net Framework version: nope. 

**Additional context**
I'm using [Astronvim](https://github.com/AstroNvim/AstroNvim) as my base config. it uses LspInstaller, and lspconfig. I'm using no special config past that.

**Comment by cannorin** [comment] 2022-09-02 12:09
Duplicate of https://github.com/ionide/Ionide-vim/issues/43. 

> But the behaviour is the same if instead I just use fsautocomplete directly with `require'lspconfig'.fsautocomplete.setup{}` which uses a local install of the latest fsautocomplete.

This means that, we have to either fix neovim or FsAutoComplete to get rid of this. Unfortunately I suspect there is nothing we can do on Ionide-vim's end.

**Closed by cannorin** 2022-09-02 12:09 UTC
Labels: bug
