### ISSUE TITLE
number of references not displaying until I do FSharpUpdateServerConfig

### ISSUE THREAD

**Issue by quantum-booty** [ionide/Ionide-vim#54] opened 2022-03-13 13:07 UTC
before:
![image](https://user-images.githubusercontent.com/28958399/158060762-f34e485b-6948-48bc-a8a7-9f7cf6b3ca81.png)

after:
![image](https://user-images.githubusercontent.com/28958399/158060773-5205740c-5cb4-4db5-89b5-6e596f819e46.png)

**Comment by cannorin** [comment] 2022-03-15 07:11
This is because 1) FSAC is kind of slow to launch and 2) Neovim's LSP implementation is a bit weird in that it requests CodeLens as soon as the language server launches.

So this is a duplicate of #43:
> it seems like it has something to do with the fact FSAC is kind of "slow" to launch, so that FSAC can't respond to the initial CodeLens request. I noticed when I use LanguageClient-neovim it correctly shows CodeLens from the beginning, so I'm suspecting Neovim's LSP implementation is weird (or maybe wrong).

I suspect there is nothing we can do on Ionide-vim side.

**Comment by WillEhrendreich** [comment] 2022-06-29 12:33
I'm getting this too, but for me the refs always show as ZERO.. even when that's plainly untrue, and not just from other projects like csharp ones.

**Comment by cannorin** [comment] 2022-09-02 12:10
Closing in favor of https://github.com/ionide/Ionide-vim/issues/43. 

Note that it seems we have to either fix neovim or FsAutoComplete to get rid of this. I suspect there is nothing we can do on Ionide-vim's end.

**Closed by cannorin** 2022-09-02 12:10 UTC
Labels: bug
