### ISSUE TITLE
FSI terminal is receiving one long line (no linebreaks) on Windows

### ISSUE THREAD

**Issue by showbiz2k** [ionide/Ionide-vim#88] opened 2024-10-23 17:54 UTC
**Describe the bug**
On Windows using NVim when I use the Alt-Enter command (or :FsiEvalBuffer) to send code to FSI, the code appears in one long line and the FSI fails to process the code.

**To Reproduce**
I have installed fresh instances of LazyVim and AstroNVim on windows and both exhibit the same issue.  

**Expected behaviour**
FSI should execute the code.

I installed both LazyVim and AstroNVim on wsl ubuntu and the FSI integration works as expected.

**Screenshots**
![Image](https://github.com/user-attachments/assets/e5fc370a-de3c-4633-8e2d-12ab0fcdc10c)

**Environment (please complete the following information):**
 - OS: Windows 10 
 - Vim / Neovim version: NVIM v0.10.2
 - dotnet SDK version: .net 8.0.306
 - mono / .Net Framework version: .net 8.0

**Additional context**
I've tried to modify the fsharp#fsi_command to "dotnet fsi --readline-" (saw that in another thread) but that didn't seem to change anything.

**Comment by cannorin** [comment] 2024-10-26 13:07
At the first glance it looks like a linebreak issue. Can you check whether your code uses `LF` or `CR LF`? A minimal reproducible example is more than welcome.

**Comment by showbiz2k** [comment] 2024-10-27 12:51
Since I was moving between WSL and windows nvim instances I had checked the line endings, but it wasn't working with either line endings, however both line endings do work with WSL nvim.

Here's a minimal example using both line endings:
![Image](https://github.com/user-attachments/assets/de4b137b-e332-42aa-9720-9175ac284bdf)
![Image](https://github.com/user-attachments/assets/362c234f-33ae-4fab-a500-85618f0c1b42)
![Image](https://github.com/user-attachments/assets/91a88335-1d87-49b8-bac6-dbb483feb462)
![Image](https://github.com/user-attachments/assets/bfa05930-b197-4067-beac-2af07858e03f)

**Comment by cannorin** [comment] 2024-11-01 02:34
@showbiz2k Can you try the `fix/call-fsi-with-os-newline` branch (#90) and see if it gets fixed?

**Comment by showbiz2k** [comment] 2024-11-01 13:50
Awesome, its working for me now on windows.  Thanks for looking into it.  Should I close this, or does that wait until its merged to master?

**Comment by cannorin** [comment] 2024-11-03 05:42
@showbiz2k You don't need to do anything as it will be auto-closed after the PR is merged. Thank you for reporting!

**Closed** 2024-11-03 05:52 UTC
Labels: bug
