### ISSUE TITLE
Workspace fails to load automatically

### ISSUE THREAD

**Issue by madetara** [ionide/Ionide-vim#22] opened 2020-01-10 14:21 UTC
**Describe the bug**
The title is quite self-explainatory. 
Workspace doesn't load automatically.
After calling `:FSharpLoadWorkspaceAuto` everything works as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create and enter empty folder
2. Run `dotnet new web -lang F#`
3. Run `nvim Startup.fs`

**Expected behaviour**
Project loads automatically

**Environment:**
 - OS: Ubuntu 18.04 on Windows 10 (WSL) Kernel: 4.4.0-18362-Microsoft
 - Neovim version: 0.5.0-dev
 - dotnet SDK version: 3.1.100
 - mono version: 6.6.0.161

**Additional context**
<details>
  <summary>init.vim</summary>

```viml
syntax enable
filetype plugin indent on

" Relative line numbering
set relativenumber

" Leader key setting
nnoremap <Space> <nop>
let mapleader=" "

" Better search
set ignorecase
set smartcase

" Three lines scrolling
set scrolloff=3

set background=dark
set termguicolors

" Vim-plug plugins
call plug#begin()

" Vim status line plugins
Plug 'vim-airline/vim-airline'

" Iceberg color scheme
Plug 'cocopon/iceberg.vim'

" tmux status bar generator
Plug 'edkolev/tmuxline.vim'

" Netrw extension
Plug 'tpope/vim-vinegar'

" Autocompletion framework
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

" Language Server Protocol
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

" Better selection UI
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

Plug 'junegunn/fzf.vim'

" F# Language server
Plug 'ionide/Ionide-vim', { 'do': 'make fsautocomplete' }

" Function singatures plugin
Plug 'Shougo/echodoc.vim'

call plug#end()

" Color scheme config
colo iceberg
let g:airline_powerline_fonts = 1
let g:airline_theme = 'iceberg'

" Setting netrw to tree view
let g:netrw_liststyle = 3

" Make netrw take only 25% of screen space
let g:netrw_winsize = 25

" Enabling Autocompletion
let g:deoplete#enable_at_startup = 1

" Echodoc config
set cmdheight=2
let g:echodoc#enable_at_startup = 1
let g:echodoc#type = 'signature'

" Always show signcolumn
set signcolumn=yes

set updatetime=2000

" Language server config
set hidden

let g:LanguageClient_serverCommands = {}


function SetLSPShortcuts()
  nnoremap <leader>ld :call LanguageClient#textDocument_definition()<CR>
  nnoremap <leader>lr :call LanguageClient#textDocument_rename()<CR>
  nnoremap <leader>lf :call LanguageClient#textDocument_formatting()<CR>
  nnoremap <leader>lt :call LanguageClient#textDocument_typeDefinition()<CR>
  nnoremap <leader>lx :call LanguageClient#textDocument_references()<CR>
  nnoremap <leader>la :call LanguageClient_workspace_applyEdit()<CR>
  nnoremap <leader>lc :call LanguageClient#textDocument_completion()<CR>
  nnoremap <leader>lh :call LanguageClient#textDocument_hover()<CR>
  nnoremap <leader>ls :call LanguageClient_textDocument_documentSymbol()<CR>
  nnoremap <leader>lm :call LanguageClient_contextMenu()<CR>
endfunction()

" Only enables LSP mappings for following files
augroup LSP
  autocmd!
  autocmd FileType cpp,c,fsharp call SetLSPShortcuts()
augroup END

" F# hover tooltip
if has('nvim') && exists('*nvim_open_win')
  augroup FSharpShowTooltip
    autocmd!
    autocmd CursorHold *.fs,*.fsi,*.fsx call fsharp#showTooltip()
  augroup END
endif

" F# LSP things
let g:fsharp#workspace_peek_deep_level = 4
let g:fsharp#automatic_workspace_init = 1
```
</details>

**Comment by cannorin** [comment] 2020-01-14 12:01
Failed to reproduce on Neovim 0.4.3, Debian sid, .NET Core SDK 3.0.101. I'll install 0.5.0 and retry.

**Comment by madetara** [comment] 2020-01-14 22:09
I actually am not sure if it's a problem with the plugin itself. 
It might be something WSL-related

I can provide you with additional debug info, if you describe how to collect it

**Comment by cannorin** [comment] 2020-01-15 03:05
https://github.com/ionide/Ionide-vim/blob/master/ftplugin/fsharp.vim#L76-L81 is the code for automatic loading. Since `:FSharpLoadWorkspaceAuto` is working, `fsharp#loadWorkspaceAuto()` seems to be not the root of the problem. So I suppose `autocmd` is not triggered for some reason.

**Comment by cannorin** [comment] 2020-02-05 12:48
I happened to have a Windows machine so I will investigate this.

**Comment by cannorin** [comment] 2020-02-07 06:33
And I can reproduce it on WSL, both on Debian buster + nvim 0.3.4 and Ubuntu 18.04 + nvim 0.5.0.

Maybe it's because of the WSL things or the fresh installation is broken in the first place. I'll try it out on a fresh native Linux environment to see if the latter is the case.

**Comment by stroborobo** [comment] 2020-03-03 15:44
Since it just broke on my machine after a PlugUpdate, I've tried a few past versions of LanguageClient-neovim and it seems to have broken with 0.1.156. It works fine on tag 0.1.155.

git bisect'ing showed [13729a415](https://github.com/autozimu/LanguageClient-neovim/commit/13729a415) to be the first bad commit. Since the binary stays the same, it could only be in the `autoload/LanguageClient.vim`. I don't really understand VimL well and don't see the bug right now. But maybe this helps? It looks like the breaking change autozimu mentioned in [the Updates issue](https://github.com/autozimu/LanguageClient-neovim/issues/35#issuecomment-576489039).

**Comment by stroborobo** [comment] 2020-03-03 18:04
So if I always return `Ok(Value::Null)` in their `textDocument_codeLens` it works perfectly. I've got a feeling that FSAC is just not fast enough, because if I remove the codeLens call from [here](https://github.com/autozimu/LanguageClient-neovim/blob/222e250/src/language_server_protocol.rs#L2110) it works fine, later codeLens calls seem to be going though, at least there's no error in the logs.

Doesn't seem to be an ionide-vim problem.

**Comment by cannorin** [comment] 2020-03-09 05:08
Hmm, I think it's better to open an issue in their repo and stick to < 0.1.156 for now. They have too many issues and it seems less likely to get fixed soon, though.

**Comment by cannorin** [comment] 2020-03-19 05:13
I created an issue there: https://github.com/autozimu/LanguageClient-neovim/issues/994. Sorry for the delay :bowing_man:

**Comment by cannorin** [comment] 2020-03-19 05:27
@stroborobo Thanks for the investigation btw! It helped me a lot :smile:

**Comment by stroborobo** [comment] 2020-03-19 09:00
Nothing to be sorry about, I should have probably done that in the first place. So thanks for taking care of it :)

**Comment by Parasrah** [comment] 2020-03-28 22:07
I'm not sure if this is related or not, but I was experiencing similar issues but thought it was related to my environment. I ended up with the following as a workaround:
https://github.com/ionide/Ionide-vim/compare/master...Parasrah:fix-workspace-discovery

**Comment by cannorin** [comment] 2020-03-29 08:12
@Parasrah when finding a workspace, FSAC is designed to dig into child directories but not the parent. Ionide-vim uses the directory of the F# file (which means it can't load the fsproj/sln at the parent directory) but I'm thinking we should just use the current directory of (neo)vim instead.

**Comment by cannorin** [comment] 2020-06-18 02:06
Since there is no sign of https://github.com/autozimu/LanguageClient-neovim/issues/994 getting fixed, I'm starting to think we should migrate to some other language client.

**Comment by PhilT** [comment] 2020-06-21 21:02
I'm currently using coc-fsharp but I'd be willing to help out with integrating something to get ionide-vim working. https://github.com/prabirshrestha/vim-lsp looks to be actively maintained although I've no experience using it.

**Comment by cannorin** [comment] 2020-06-21 22:16
Yes, I'm thinking ale and vim-lsp for viable candidates.

**Comment by cannorin** [comment] 2020-11-05 00:03
https://github.com/autozimu/LanguageClient-neovim/issues/994 is actually fixed! Once it's merged to the `next` branch of LC-neovim I think I can close this issue and continue the discussion of the other LSP implementations in #5,

**Closed** 2021-06-27 09:23 UTC
Labels: bug
